# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(405, 390)
        Form.setMinimumSize(QtCore.QSize(405, 380))
        Form.setMaximumSize(QtCore.QSize(405, 390))
        Form.setBaseSize(QtCore.QSize(405, 380))
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 401, 391))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.check_novosibirsk = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_novosibirsk.setObjectName("check_novosibirsk")
        self.gridLayout.addWidget(self.check_novosibirsk, 4, 0, 1, 1)
        self.check_pyatigorsk = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_pyatigorsk.setObjectName("check_pyatigorsk")
        self.gridLayout.addWidget(self.check_pyatigorsk, 4, 1, 1, 1)
        self.check_ufa = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_ufa.setObjectName("check_ufa")
        self.gridLayout.addWidget(self.check_ufa, 5, 1, 1, 1)
        self.check_samara = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_samara.setObjectName("check_samara")
        self.gridLayout.addWidget(self.check_samara, 5, 0, 1, 1)
        self.check_spb = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_spb.setObjectName("check_spb")
        self.gridLayout.addWidget(self.check_spb, 0, 1, 1, 1)
        self.check_nalkhik = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_nalkhik.setObjectName("check_nalkhik")
        self.gridLayout.addWidget(self.check_nalkhik, 3, 0, 1, 1)
        self.check_krasnodar = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_krasnodar.setObjectName("check_krasnodar")
        self.gridLayout.addWidget(self.check_krasnodar, 2, 0, 1, 1)
        self.check_chelyabinsk = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_chelyabinsk.setObjectName("check_chelyabinsk")
        self.gridLayout.addWidget(self.check_chelyabinsk, 1, 0, 1, 1)
        self.check_moscow = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_moscow.setObjectName("check_moscow")
        self.gridLayout.addWidget(self.check_moscow, 0, 0, 1, 1)
        self.check_nijnyynovgorod = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_nijnyynovgorod.setObjectName("check_nijnyynovgorod")
        self.gridLayout.addWidget(self.check_nijnyynovgorod, 3, 1, 1, 1)
        self.check_novorossijk = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_novorossijk.setObjectName("check_novorossijk")
        self.gridLayout.addWidget(self.check_novorossijk, 2, 1, 1, 1)
        self.check_voronezh = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_voronezh.setObjectName("check_voronezh")
        self.gridLayout.addWidget(self.check_voronezh, 1, 1, 1, 1)
        self.check_cheboksari = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_cheboksari.setObjectName("check_cheboksari")
        self.gridLayout.addWidget(self.check_cheboksari, 6, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 6, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Parser russteels"))
        self.check_novosibirsk.setText(_translate("Form", "Новосибирск"))
        self.check_pyatigorsk.setText(_translate("Form", "Пятигорск"))
        self.check_ufa.setText(_translate("Form", "Уфа"))
        self.check_samara.setText(_translate("Form", "Самара"))
        self.check_spb.setText(_translate("Form", "Санкт-Петербург"))
        self.check_nalkhik.setText(_translate("Form", "Нальчик"))
        self.check_krasnodar.setText(_translate("Form", "Краснодар"))
        self.check_chelyabinsk.setText(_translate("Form", "Челябинск"))
        self.check_moscow.setText(_translate("Form", "Москва"))
        self.check_nijnyynovgorod.setText(_translate("Form", "Нижний Новгород"))
        self.check_novorossijk.setText(_translate("Form", "Новороссийск"))
        self.check_voronezh.setText(_translate("Form", "Воронеж"))
        self.check_cheboksari.setText(_translate("Form", "Чебоксары"))
        self.pushButton.setText(_translate("Form", "Спарсить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
